### ISSUE TITLE
Move PVnet to separate repo

### ISSUE THREAD

**Issue by carderne** [openclimatefix/PVNet#1]
Below copied from: https://github.com/openclimatefix/predict_pv_yield/issues/112
@peterdudfield

## Detailed Description
Move PVnet to separate repo, so that we can install this separately, and do improvements there.
Code is [here](https://github.com/openclimatefix/predict_pv_yield/blob/main/predict_pv_yield/models/conv3d/model_sat_nwp.py)
[image](https://github.com/openclimatefix/predict_pv_yield/blob/main/predict_pv_yield/models/conv3d/conv3d_sat_nwp.png)

## Context
Good to break it up a bit, then ready to https://github.com/openclimatefix/PVNet/issues/2 or SBRI project

## Possible Implementation
- [x] make new [repo](https://github.com/openclimatefix/PVNet/)
- [x] move code there
- [x] move [tests](https://github.com/openclimatefix/predict_pv_yield/blob/main/tests/models/conv3d/test_conv3d_model_sat_nwp.py) there
- [x] add CI
- [x] add library to pypi

**Comment by peterdudfield** [comment]
@carderne Ill have to send you a Pypi env variable. 

see other github actions for releasing a package [here](https://github.com/openclimatefix/.github/blob/main/.github/workflows/python-release.yml)
