### ISSUE TITLE
Add placeholders to configs

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/PVNet#103]
To allow many users to train this model themselves, remove the hard coded paths from the configs and add the configs to the .gitgnore. Users can edit the configs locally to their own paths

**Comment by confusedmatrix** [comment]
Is there any risk to existing installations of PVNet (e.g. in production) that really on these configs if we add them to .gitignore? The configs that currently exist should probably serve as defaults that can be overridden with hydra on the command line with custom configs (not sure if this already happens in our production environment)

**Comment by dfulu** [comment]
No there is no risk. The configs for production are version-controlled alongside the model [on huggingface](https://huggingface.co/openclimatefix/pvnet_v2/tree/main) since each trained model might have different settings
