### ISSUE TITLE
Transfer batch transformation functions to `ocf_datapipes`

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/PVNet#111]
Transfer the `copy_batch_to_device` and `batch_to_tensor` functions from `pvnet/data/utils.py` to ocf_datapipes. These functions are specific to the NumPyBatch object in datapipes, so I think it makes sense for them to go there

**Comment by aryanbhosale** [comment]
> Transfer the `copy_batch_to_device` and `batch_to_tensor` functions from `pvnet/data/utils.py` to ocf_datapipes. These functions are specific to the NumPyBatch object in datapipes, so I think it makes sense for them to go there
Hi @dfulu , I'm unable to find ocf_datapipes. Could you please help me out here?

**Comment by markus-kreft** [comment]
Hi all,

I have just opened https://github.com/openclimatefix/ocf_datapipes/pull/287. Once discussions on type hints there are done and it is merged, I have a PR ready to make use of the functions.

@aryanbhosale: I started looking into this yesterday and only now saw that you are also working on it. But I would be very happy about feedback on my PR if you are also interested in this issue.

**Comment by dfulu** [comment]
Hi both, thanks very much for jumping on this! 

@aryanbhosale I'm sure you've found ocf_datapipes by now, but here it is anyway: https://github.com/openclimatefix/ocf_datapipes

It looks like the two of you have this handled. Let me know if you have any more questions and please feel free to tag me directly in any pull requests
