### ISSUE TITLE
India Wind v2

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#133]
Add new NWP provider to PVnet, to be decided which one

**Comment by jacobbieker** [comment]
I think for v2, it would be using other NWP providers as well for the wind forecast. I already use all the NWP variables we do have

**Comment by peterdudfield** [comment]
Yes, you are totally right, add a new NWP provider, i will update

**Comment by peterdudfield** [comment]
Ive deployed the larger batches sizes on development
