### ISSUE TITLE
PVnet more NWP variables

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#134]

**Comment by jacobbieker** [comment]
This I think would be more NWPs to use. I already am using all the NWP variables relevant for solar from ECMWF for India

**Comment by peterdudfield** [comment]
Yea, but I think in the UK, the Current PVnet wasnt using many variables. So it was to get PVnet using more variables for the UK. @dfulu right?

**Comment by dfulu** [comment]
Yeh that's right. The current PVNet only uses 2 variables from UKV. But if this is for PVNet in the UK then maybe it makes more sense to have it assigned to me rather than Jacob?

**Comment by peterdudfield** [comment]
Thanks @dfulu

**Comment by peterdudfield** [comment]
Need https://github.com/openclimatefix/ocf-infrastructure/issues/437 before going live

**Comment by dfulu** [comment]
This is now completed with the new model
