### ISSUE TITLE
`hindcast.py` is out of date

### ISSUE THREAD

**Issue by markus-kreft** [openclimatefix/PVNet#156]
## Describe the bug
When looking into https://github.com/openclimatefix/PVNet/issues/111 to move utility functions to `ocf_datapipes` I found a regressions. PVNet depends on [`ocf_datapipes>=3.1.5`](https://github.com/openclimatefix/PVNet/blob/7e1dd3b8e75c4eac4a5cf756c1831666614ed168/requirements.txt#L1C1-L1C21) so the latest version will be installed. In [`hindcast.py`](https://github.com/openclimatefix/PVNet/blob/7e1dd3b8e75c4eac4a5cf756c1831666614ed168/scripts/hindcast.py#L16C39-L16C67), the function `stack_np_examples_into_batch` is imported from `ocf_datapipes.utils.utils`, however, [21b0f95](https://github.com/openclimatefix/ocf_datapipes/commit/56b243d231a36aed14c2af136a7f943d8cf72f51#diff-2d84f41d5fd910926242da691c61382f289af0215bef703ffe835f60b8a607d2) moved it to `ocf_datapipes.batch`. It is already imported correctly in e.g. `pvnet/data/datamodule.py`.

## To Reproduce
- Clone repository and install dependencies as described in Readme.
- Run `scripts/hindcast.py`
- Observe `ImportError: cannot import name 'stack_np_examples_into_batch' from 'ocf_datapipes.utils.utils'`

## Expected behavior
Import works.

**Comment by dfulu** [comment]
Hi @markus-kreft, thanks very much for flagging this. That script has unfortunately gone out of date with the library. I have a new copy that adds some extra functionality but needs a little tidying up, so I'll fix this as soon as I get the chance.

For now, if you are working on anything else, don't worry about this script running

**Comment by markus-kreft** [comment]
Thanks for clarifying. Makes also sense then that some other imports did not work as expected. I will leave this for now, but am happy to help clean up/add to CI when you added the extra functionality.

**Comment by dfulu** [comment]
Closed by #175
