### ISSUE TITLE
Use less satellite delay in PVNet UK

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/PVNet#167]
~~THIS IS CURRENTLY BLOCKED - SEE BOTTOM~~

We are currently using a constant 1 hour delay for the satellite in PVNet UK. The accuracy which we gain from satellite data, and which comes in the first couple of hours of forecast horizon, is very dependent on the satellite delay we use.

By comparing horizon accuracies, I think we should be able to decrease our 0-2 horizon error by about 3-4% (relative) if we could get the delay down to a constant 30 minutes (and even better if we could get it lower).

Peters info on production:

> The slight issue is, lots of the satellite data becomes available around 5 past the hour. So for example at 11.05 the data for 10 to 11 becomes available. This means at 11.00 there is 1 hour delay. Also it might take 10ish minutes to pull the data
Currently PVNet runs at 11.15 and 11.45. At 11.15 the 11.00 time stamp is available (normally), but at 11.45 only, the 11.00 is available. 
>
> But when PVNet is run at 11:15 (11:45) it is using an init time as if it were 11:00 (11:30). So we should have the data we need to decrease the satellite delay by 30 minutes.

Currently the RSS (5-minutely) is down for routine maintenance. Based on the current production logs the delay of the 15 minutely data is less than 15 minutes. So at 11:15, when PVNet is making a prediction as if it was 11:00, the timestamp for 11:00 is available to be used.

~~This is currently blocked.~~ We need to wait to see what delay the pvnet_app really sees the satellite data as being in production. The RSS satellite should be back up on 29th Feb

**Comment by dfulu** [comment]
Note the intuition of how much the less satellite delay would help is based on the horizon accuracy figure below. For the models which used the satellite, if we used a zero minute satellite delay, I'd expect the loss at any horizon `h` to decrease to the loss at the horizon `h-1` (i.e. that all the loss curves would be shifted 1 hour to the right). So the loss at 2 hours would decrease to a similar loss to what we see at 1 hour horizon. This is an approximation, and of course the NWP inputs are not becoming an hour less delayed, but based on the fact that the NWP-only curves here have a low gradient, I think its a reasonable expectation.

![Image](https://github.com/openclimatefix/PVNet/assets/41546094/b6370b03-160f-46a5-a84c-b9309844dd01)

**Comment by peterdudfield** [comment]
note that PV net live current runs at XX:15 and XX:45, so I think its right that t0 is XX:00 would have satellite data for that time. 

One thing perhaps to check beforeing deploy is to check that this is the same when 15 satellite is being used

**Comment by jacobbieker** [comment]
"Luckily" for this, the 5 minute data stops for 48 hours tomorrow morning, so we should be able to see soon how long the delay is with the 15 minute data.
