### ISSUE TITLE
Not all model config values logged accurately in weights & bias UI

### ISSUE THREAD

**Issue by Sukh-P** [openclimatefix/PVNet#168]
## Describe the bug
Currently when using W&B as the logger when training a model using PVNet not all config parameters seem to show accurately in the W&B UI, some show as `null` even when they are non null. 

See example screenshot:
<img width="725" alt="Screenshot 2024-03-26 at 10 42 39" src="https://github.com/openclimatefix/PVNet/assets/42407101/d95d2ab1-109b-431d-b1e3-8f5618c83bb8">

## To Reproduce
Train a model using PVNet and use W&B as the logger and look at the config pane on the overview page of the run and compare the config that was actually used (should be saved in a local file when running PVNet). 

## Expected behaviour
Would expect W&B to log all the model config accurately so that comparisons can be made between different runs with different configs (not that currently a local config parameter file is produced so this information is not lost but would be favourable  

## Additional context
This seems to only happen for section of the config which have [formats such as this in the multimodal.yaml file](https://github.com/openclimatefix/PVNet/blob/main/configs.example/model/multimodal.yaml#L96), where `_target_` is the first key on the second level. Most likely is an issue with W&B parsing config in this specific format

**Comment by peterdudfield** [comment]
Good to note its not a `wandb` issue as this works
```
import wandb

wandb_logger = dict(_target_="lightning.pytorch.loggers.wandb.WandbLogger",
                    project="wandb_test",
                    name="test_mode",
                    save_dir="wandb_test",
                    offline=False,  # set True to store all logs only locally
                    log_model=False,
                    job_type="train",
                    optimizer = dict(_target_="torch.optim.Adam", lr=0.1)
                    )

experiment = wandb.init(config=wandb_logger)
experiment.log({"loss": 0.1})
```

**Comment by peterdudfield** [comment]
Also doesnt seem to be a problem with pytorch lightning
```
logger = WandbLogger(
    project="wandb_test",
    name="test_mode",
    save_dir="wandb_test",
    offline=False,  # set True to store all logs only locally
    log_model=False,
    job_type="train",
)
logger.log_hyperparams({"optimmizer":{"_target_":"torch.optim.Adam","lr": 0.1}})
logger.experiment.log({ "loss": 0.1})
```
works, so my guess is its a hydra issue

**Comment by peterdudfield** [comment]
It looks like its happens in 
```
OmegaConf.save(config.model, f"{callback.dirpath}/model_config.yaml")
```
in pvnet/training.py

**Comment by peterdudfield** [comment]
The file seems to appear once the `trainer.fit` phase has begun

**Comment by peterdudfield** [comment]
Whats also weird, is this config seems to save just the just the `model` configs, but other configs

**Comment by peterdudfield** [comment]
Ill close this now, as the PR #217 should fix this
