### ISSUE TITLE
Increasing Capacity UK

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#187]
## Detailed Description
In the backtest we use continuous increase effective capacity (need to check this) and use this to normalise the PV Live values. This is used for training. Currently in live the effective capacity slowly drifts down and then jumps up when PVlive update it. This is different from real life and can lead to some errors

Live effect capacity

## Context
- we train our model using values between 0-1 for pv solar genertion. So we need a really accuray capacity in order to up scale these things. 

## Possible Implementation
- Look at the last two updates of capacity, and extroplate linear from there to get the extra capacity right now. 
- Still use ffective capacity, as this takes into account degradation

**Comment by peterdudfield** [comment]
<img width="1344" alt="Screenshot 2024-05-09 at 18 18 00" src="https://github.com/openclimatefix/PVNet/assets/34686298/824c79ff-3af4-409d-8ca6-59e7fd4f0a0d">

Here's the date for the last 1.5 years

**Comment by peterdudfield** [comment]
Asked on here - https://github.com/SheffieldSolar/PV_Live-API/issues/36

**Comment by peterdudfield** [comment]
On second thoughts, PVLive probably uses this step values for the estimate, so we should use these value to best estimate the PVLive out turns

**Comment by dantravers** [comment]
Yep, I think I agree with the last comment - we will be assessed versus PV_Live, but agree for modelling net demand the increasing demand would make sense.

**Comment by peterdudfield** [comment]
as discussed with PVLive, ill close this for the moment
