### ISSUE TITLE
Extended horizon PVNet backtest (incl 2023)

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#204]

**Comment by zakwatts** [comment]
This has been put on pause for now until we wait for the new model improvements to happen

**Comment by zakwatts** [comment]
Waiting to start after completing: https://github.com/orgs/openclimatefix/projects/33/views/8?filterQuery=assignee%3Azakwatts&pane=issue&itemId=60827379

**Comment by zakwatts** [comment]
Complete and will report in other issue about follow up tasks
