### ISSUE TITLE
Windnext : XG boost

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#220]
## Detailed Description
Instead of using PVnet, we should try using xgb

## Context
- Good to get a comparison of PVnet
-  It might do better
- Would like to improve Wind DA forecast
- Current wind is done using PVnet site pipeline
- batches are at the moment here: "/mnt/storage_u2_4tb_b/windnet_india_batches_large_all_nwp" on donatello

## Possible Implementation
- [x] #221
- [x] #222
- [x] train model 
- [x] compare

**Comment by Sukh-P** [comment]
@peterdudfield would you say this is done with the work @ADIMANV has done now to train the XGB model and do some comparisons?

**Comment by peterdudfield** [comment]
I think so
