### ISSUE TITLE
Analysis of windspeed and location correlation vs wind energy. windspeed= (u2 + v2)^0.5. take 100.

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#221]
Use windspeed= (u2 + v2)^0.5. take 100.

1. Loop over all lat and longs
2. For each lat lon, get the wind speed for all batches.
3. For each lat lon, work out correlation with wind energy
Could take first 100 samples to speed things up

**Comment by Sukh-P** [comment]
Was able to create images like these from individual samples which show correlation between wind speed and power per lat long over one NWP init time (50 hours), now trying to see how easy it will be to try and do this with 100 samples without it taking a long time or running out of memory 
 
<img width="1021" alt="Screenshot 2024-06-18 at 10 09 42" src="https://github.com/openclimatefix/PVNet/assets/42407101/9ea25d79-0e98-49f3-be9d-41fd139436f2">

**Comment by peterdudfield** [comment]
Great stuff @Sukh-P, yea adding more samples and more init should start to un blurr this image

**Comment by Sukh-P** [comment]
Here is the plot with 100 samples, with 50 steps each:

<img width="1021" alt="Screenshot 2024-06-20 at 09 09 11" src="https://github.com/openclimatefix/PVNet/assets/42407101/e037b282-7fd2-4019-a3a0-6988147da701">

So does chime with what has been told before that most of the turbines are in the west of Rajasthan which seems like the most highly correlated area (0.8), around 27.2, 71.1. 

Could be interesting to shift the centre of the crop to the left or try and get a crop that focuses more on that left side.

**Comment by peterdudfield** [comment]
That is a lovely plot!

This will help us when we want to reduce the data down to say 9 points for teh XGbosst model. We can take nothing above 74, and between 24 and 29. 

Yea we could shift left a bit, althought im not sure the ECMWF dataset has any more data. Interestingly the wind not in Rajistan could be highly correlated to the wind in Rajiston in certain areas, which would lead to a high correlation of wind speed vs wind energy, but perhaps we still shouldnt include this data, as it not in Rajistan. Im not sure though?

**Comment by Sukh-P** [comment]
Yeah it's hard to know, I guess in an ideal situation we would run an experiment with a slightly modified crop to test those theories, but obviously that depends on how much time it would take to do that. I guess by changing the lat long of the site and modifying the width, height there could be a way to get a sub crop of this one centred a bit more to the left.
