### ISSUE TITLE
Change batches into dataframe

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#222]
- filter area depending on #221 
- load all batchs and coarsen to 4 by 4 grid (xr.coarsen)
- just take 1 hour wind energy data 
- use train and validation folders 

| Time    | Target_time | Step | u10_0 | ... | u10_15 | v10_0 | wind energy |
| -------- | ------- | ------- | ------- |------- |------- | ---- | --- |
| 2023-01-01  | 2023-01-01 | 0   | 0   | 0   | 0   | 0   | 0   | 0 | 0.5
| 2023-01-01 | 2023-01-01  01:00 | 1     |  0   | 0   | 0   | 0   | 0   | 1000
| 2023-01-01  | 2023-01-01  02:00 | 2    | 0   | 0   | 0   | 0   | 0   | 2000

**Comment by Sukh-P** [comment]
@peterdudfield just to check which ECMWF variables should I take for this? The batches have 16 in them but not sure if you want them all or just the ones listed here https://huggingface.co/openclimatefix/windnet_india/blob/main/data_config.yaml?

**Comment by peterdudfield** [comment]
yea, i'd start with those 7

**Comment by Sukh-P** [comment]
Outputs from this have been put [here](https://drive.google.com/drive/folders/1_SagS6sm7wvleIWq1HPWnNvRQk5QfOnp?usp=drive_link) the training data is from 20,000 samples used in training for the Windnet model that have been converted into a dataframe, the csv is around a million rows and 100 columns, the validation data is roughly 15% the size of the training data (made up of around 3,000 samples). Will let others review the outputs to check is nothing is missing. 

Some thoughts:

- Could be interesting to modify this dataset to include additional columns like windspeed `(u**2 + v**2)**0.5` at the different lat long locations (just u and v 100) alongside the existing NWP channels 
- Would be interesting to have the dataset with just windspeed at the lat long locations without the NWP channels to see how much impact the channels by themselves have
