### ISSUE TITLE
Saving model to HF broken _save_pretrained method doesn't exist

### ISSUE THREAD

**Issue by Sukh-P** [openclimatefix/PVNet#249]
## Describe the bug
Currently when trying to save a model to HF with the code in the main branch one would encounter this error:
```
AttributeError: 'Model' object has no attribute '_save_pretrained'
```

I believe this happens now since in [this commit](https://github.com/openclimatefix/PVNet/commit/e3427e53ec52661e37150b523c4a31183c58db7f#diff-8cc8a79916f89397360949f4557c1fb1789a01fb0c9a20e6af2eb069b6871889L144) the `PyTorchModelHubMixin` class was removed, it turns out that we were using the [_save_pretrained](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hub_mixin.py#L766) method from it in our [base model save_pretrained method](https://github.com/openclimatefix/PVNet/blob/main/pvnet/models/base_model.py#L278)

So I think there are two ways this could be fixed:
- Either by reintroducing the `PyTorchModelHubMixin` and inheriting from it
- Or if the `PyTorchModelHubMixin` is unnecessary overhead just for that one method (I am assumed it isn't used elswhere) we could implement our own  '_save_pretrained' method to save model weights locally, wouldn't be too hard I think since the method HF uses looks quite straightforward, I tried just a torch.save() replacement but that seems to not quite work but hopefully not too much more complicated than something like that, @peterdudfield would be good to get your opinion as you probably have most context for the pros/cons of removing the `PyTorchModelHubMixin` class

**Comment by peterdudfield** [comment]
Interesting, do you know wen this PytorchModelHubMixin was removed? and why?

I guess it was removed to make it cleaner? or there was some comptability issue?

**Comment by Sukh-P** [comment]
@peterdudfield I think the commit with that change was created by yourself https://github.com/openclimatefix/PVNet/pull/238/files so I was hoping you may be able to shed some light on that part 😄

**Comment by peterdudfield** [comment]
ah, not sure, my mistale for not testing it properly, is it easy to put back in?

**Comment by Sukh-P** [comment]
Yep it is straight forward, just wanted to check there wasn't a specific reason we wanted to remove it since as I mentioned I think we could implement something ourself to avoid using it
