### ISSUE TITLE
run_app_locally.py outdated? 

### ISSUE THREAD

**Issue by gabrielelibardi** [openclimatefix/PVNet#257]
If I try to run scripts/run_app_locally.py I get this error 
    from pvnet.app import app
ModuleNotFoundError: No module named 'pvnet.app'

I don't see any app.py file in the repo, is this script outdated or am I doing something wrong?

**Comment by peterdudfield** [comment]
Yea this is outdated, I think this should be moved to https://github.com/openclimatefix/uk-pvnet-app/tree/main/scripts

**Comment by Sukh-P** [comment]
Thanks for pointing this out, created a PR to get rid of the script now, as Peter mentioned that functionality is now in in the [uk-pvnet-app](https://github.com/openclimatefix/uk-pvnet-app)[https://github.com/openclimatefix/uk-pvnet-app](https://github.com/openclimatefix/uk-pvnet-app/tree/main/scripts) repo
