### ISSUE TITLE
Production performance

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#30]
Just managed to analysis the last 2 weeks of data using the analysis dashboard

| Forcast Horizon      | PVnet 1.0 | National_xg | Pvnet 2.1 | Best
| ----------- | ----------- | ----------- | ----------- | ----------- |
| 0       | 179       | 300 | 259| PVnet 1.0
| 60   | 241        | 363| 249 | PVnet 1.0
| 120       | 271       | 359| 228|  PVnet 2.1
| 240       | 335       | 366| 247 |  PVnet 2.1
| 420       | 432       | 377 |  272 |  PVnet 2.1 | 

and `National_xg` is the only model that runs pass 8 hours

![Screenshot 2023-06-20 at 20 21 09](https://github.com/openclimatefix/PVNet/assets/34686298/e510847d-4b71-42f3-acfd-0473c15b400b)

**Comment by peterdudfield** [comment]
I would be tempeted to blend the forecast using these weights

PVnet 1.0 -> PVnet 2.1 -> National_xg

| Forcast Horizon      | PVnet 1.0 | National_xg | Pvnet 2.1 |
| ----------- | ----------- | ----------- | ----------- | 
| 0       | 1.0      | 0 | 0| 
| 60   | 0.5        | 0| 0.5 | 
| 120       | 0       | 0| 1.0|  
| 240       | 0       | 0| 1.0 |  
| 360       | 0       | 0| 1.0 |  
| 420       | 0       | 0.5 |  0.5 |  
| 480       | 0       | 1.0 |  0 |

**Comment by peterdudfield** [comment]
2023-06-27 to 2023-07-10
Cnn
![Screenshot 2023-07-10 at 12 13 04](https://github.com/openclimatefix/PVNet/assets/34686298/9c86d60d-5d56-4560-8484-f1544275c3a6)

Pvnet
![Screenshot 2023-07-10 at 12 14 40](https://github.com/openclimatefix/PVNet/assets/34686298/e74ccbc6-75c2-40d3-8596-5e7ac390a3b3)


Cnn with adjuster
![Screenshot 2023-07-10 at 12 15 07](https://github.com/openclimatefix/PVNet/assets/34686298/463aa0af-871a-4f9c-bffd-ec483604ab82)



PVnet with adjuster
![Screenshot 2023-07-10 at 12 14 46](https://github.com/openclimatefix/PVNet/assets/34686298/23b96bbf-4abc-42d9-aa5d-c3f4373637b1)

**Comment by peterdudfield** [comment]
Also we are checking if there are problems when the Sat consumer switches from 5 mins to 15 mins. 

- 2023-07-11 11:00, changed Satelilte consumer to get 15 mins data 
-

**Comment by dfulu** [comment]
Closing since I think these values are out of date now
