### ISSUE TITLE
Deal with satellite outages

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/PVNet#31]
Sometimes, on a[ fairly regular schedule](https://www.eumetsat.int/rapid-scanning-service-schedule), the rapid refresh satellite data that we use to run the model in production goes offline. Usually for a 2-day period each month.

This can cause a degradation in model performance like happened on 20th June.
<img width="766" alt="Screenshot 2023-06-21 at 14 32 36" src="https://github.com/openclimatefix/PVNet/assets/41546094/f764f87d-4701-41d1-80a9-0fc114877b86">

When the rapid refresh is down the 15-minutely data still exists, and PVNet1 used this. See [here](https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/satellite/satellite_data_source.py#L154). We could try a similar solution for PVNet2, maybe in combination with training a model specifically for this circumstance

**Comment by peterdudfield** [comment]
Thanks @dfulu for putting this here,

**Comment by peterdudfield** [comment]
note: this happens when switching from the 5 min data, to 15 min data

**Comment by peterdudfield** [comment]
Could this be solved by, 
- loading 15 mins data, when 5 mins is not avaialble
- dont fill satellite data with zeros? 

Thoughts @dfulu

**Comment by peterdudfield** [comment]
@dfulu we can probably close this too
