### ISSUE TITLE
Test using GSP PVLive inputs

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/PVNet#53]
Currently the model does not use any PV measurement as inputs. This is because we only have the updated PVlive estimates for each GSP and not the initial intra-day estimates. 

The updated estimates are likely to be different from the intraday estimates, but we are not sure by how much. To test their usefulness we should:

- Train a model with updated PVLive GSP inputs
- Test the trained model in the production environment with intra-day PVLive GSP inputs

**Comment by dfulu** [comment]
The validation results for the current model (no hist) and the new model which also used uses PVLive GSP live inputs is shown here. Note that this validation data also used the updated PVLive data as inputs so the performance of the new model may differ in production

![W B Chart 17_07_2023, 10_00_48](https://github.com/openclimatefix/PVNet/assets/41546094/a9c7baab-8c97-4463-b62f-817013136edc)

**Comment by peterdudfield** [comment]
Nice this is really good

**Comment by dfulu** [comment]
<img width="768" alt="Screenshot 2023-08-08 at 15 54 42" src="https://github.com/openclimatefix/PVNet/assets/41546094/22272e28-6720-4224-8795-50638d1cd77a">

Above is the results for this experiment evaluated over the period 18 July - 5th August 2023 on the national sum of GSP predictions. Using intraday PVLive inputs to the model trained on updated PVLive inputs increased the accuracy of the short term predictions but decreased the accuracy after about an hour.

**Comment by peterdudfield** [comment]
Ill just keep this open, so we remember the different between dev and production for the moment. 

One other way we could carry on here, is to deploy model PVlive for the first 1 hour, then switch to with out. Its a bit messy though

**Comment by dfulu** [comment]
Yeh, that could work, but I'd prefer to keep it all in one model ideally. I think we should wait to see the results of #68. Option 2 of that should be reasonably quick to implement

**Comment by dfulu** [comment]
Closing this, as it has become apparent that using PVLive inputs is not going to be possible and neither dev or production use it anymore
