### ISSUE TITLE
Installation inconsistency

### ISSUE THREAD

**Issue by tomasvanoyen** [openclimatefix/PVNet#61]
## Describe the bug
Hi I am trying to install PVnet. There appears to be an inconsistency in the requirements. In particular, 

PVNet asks for nowcasting_datamodel==1.4.0, and also nowcasting_utils. The latter in turn requests nowcasting_dataset, which in turn requires nowcasting_datamodel>=1.4.4. 

I do not know yet if this imposes serious problems on the code but it is inconsistent, and would be nice to resolve. 

Regards, 

Tomas

**Comment by dfulu** [comment]
Hi @tomasvanoyen, thanks for this issue. I'll look at updating the requirements

**Comment by tomasvanoyen** [comment]
okay! thanks!
