### ISSUE TITLE
inconsistent default | hard-coded values

### ISSUE THREAD

**Issue by tomasvanoyen** [openclimatefix/PVNet#63]
## Describe the bug
Some default | hard-coded values are not consistent between `scripts/save_batches.py` (making batches) and 
`run.py` (setting model dimensions). In particular, running `scripts/save_batches.py` in non-production model sets the `sat_delay` to 30 minutes (hard-coded, which is reasonable). However, running thereafter `run.py` provides as default `min_sat_delay_minutes: Optional[int] = 15`, leading (I believe) to a mismatch in dimensions expected (in particular `self.sat_sequence_len` appears to differ then). 

I guess a quick solution would be to change the default value of the `min_sat_delay_minutes`? Or remove the parameter all together as it is hard-coded in ocf_datapipes/training/pvnet.py; or make it configurable there. 

Regards, 

Tomas

**Comment by dfulu** [comment]
Hi @tomasvanoyen, thanks for the issue. I agree this should be changed. I'll update the default and also add to datapipes so the delay can be configured
