### ISSUE TITLE
run.py fails while cleaning up (utils.finish)

### ISSUE THREAD

**Issue by tomasvanoyen** [openclimatefix/PVNet#64]
## Describe the bug

`  File "/home/ubuntu/dev/openclimatefix/pvnet/pvnet/training.py", line 147, in train
    utils.finish(
  File "/home/ubuntu/dev/openclimatefix/pvnet/pvnet/utils.py", line 237, in finish
    for lg in logger:
TypeError: 'TensorBoardLogger' object is not iterable`

`utils.finish` line 147 of `pvnet/training.py` passes `logger`, but utils.finish is expecting an List of loggers.

**Comment by dfulu** [comment]
Thanks for the issue @tomasvanoyen!
