### ISSUE TITLE
bug: PVnet suddenly drops

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet#83]
## Detailed Description
PVnet seems to drop all froecasts. After running it again in 30 mins it seems fine

## Context
- see a blip in the 4 hour forecasts sometimes
- NWP consumer on dev was only fixed about for the first 9.45 run

![Screenshot 2023-08-25 at 12 55 11](https://github.com/openclimatefix/PVNet/assets/34686298/cf625486-0b5c-45f3-a2c5-ed8267a5a200)

**Comment by peterdudfield** [comment]
![image (34)](https://github.com/openclimatefix/PVNet/assets/34686298/aabb0a47-9adf-4972-88f5-b0751d9cd34c)
![newplot (11)](https://github.com/openclimatefix/PVNet/assets/34686298/9ca091e4-c05b-4117-a29c-32084b22210f)

**Comment by peterdudfield** [comment]
Idea: could be missing data in satellite - that then gets filled in with zeros.

**Comment by peterdudfield** [comment]
![Screenshot 2023-08-31 at 14 37 00](https://github.com/openclimatefix/PVNet/assets/34686298/b6972961-04a1-4f87-8a31-3e7c41675c1c)

**Comment by peterdudfield** [comment]
> ![Screenshot 2023-08-31 at 14 37 00](https://user-images.githubusercontent.com/34686298/264662429-b6972961-04a1-4f87-8a31-3e7c41675c1c.png)

But I cant seem to find this is PVnet - might have to look at logs in blend service

**Comment by peterdudfield** [comment]
![Screenshot 2023-08-31 at 14 43 02](https://github.com/openclimatefix/PVNet/assets/34686298/ae7ad329-c059-4733-95e5-c7e40f00c391)

**Comment by peterdudfield** [comment]
It was the 8.15 UTC run of PVnet 2
![Screenshot 2023-08-31 at 14 44 48](https://github.com/openclimatefix/PVNet/assets/34686298/163f0df1-0bb2-4038-9566-856204219025)

**Comment by peterdudfield** [comment]
Nothing unsual int he logs - https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252Fforecast_pvnet$252F/log-events/streaming$252Fforecast$252F2505f5d10f7b45509891cb2b804ea329$3Fstart$3D-43200000

**Comment by peterdudfield** [comment]
We do see this in GSPs 30 to 39 (inclusive) which is one batch of the PVnet run

**Comment by peterdudfield** [comment]
The batch was made and run at 8.17.51 to 8.17.57 UTC
No satellite data was uploaded then
NWP was uploaded but with no changes, at 8.17.36

**Comment by peterdudfield** [comment]
![Screenshot 2023-09-01 at 14 12 23](https://github.com/openclimatefix/PVNet/assets/34686298/866db75b-a5e2-43a2-8eff-8061ffe2abff)
Another few today on dev

**Comment by peterdudfield** [comment]
I worry its the NWP data upload that is interferrring in a small way. I could change the NWP data to run every 10,25,40,55 rather than 15,30,45,0, then its less likely to interferr

**Comment by peterdudfield** [comment]
We've seen more spikes in early gsp numbers that later ones, so this could correspond with NWP changing

**Comment by dfulu** [comment]
I think this was solved by the NWP download and the inversion fix. Closing for now
